import type { DocumentDeadlineState } from "../enums/document-deadline-state";
import type { DocumentStatus } from "../enums/document-status";
import type { DocumentKind } from "../enums/document-kind";
import type { IsoDateString } from "./common";
import type { Employer } from "./employer";
import type { User } from "./user";
import type { Resolution } from "./resolution";

export type DocumentListItem = {
  id: number;
  registrationNumber: string;
  registrationDate: IsoDateString;
  title: string;
  about1: string;
  about2: string | null;
  kind: DocumentKind;
  status: DocumentStatus;
  ownerId: number;
  executorId: number;
  employerId: number | null;
  outSenderEmployerId: number | null;
  outgoingDate: IsoDateString | null;
  broadcast: string;
  dueDate: IsoDateString;
  completedAt?: IsoDateString | null;
  isControl: boolean;
  deadlineState: DocumentDeadlineState;
  deletedAt?: IsoDateString | null;
  createdAt: IsoDateString;
  updatedAt: IsoDateString;
  lastChangedAt: IsoDateString;
};

export type DocumentDetails = DocumentListItem & {
  description: string | null;
  incomingNumber: string | null;
  outgoingNumber: string | null;
  employer: Employer | null;
  owner: User;
  executor: User;
  resolutions: Resolution[];
  lastChangedBy: User;
};

export type CreateDocumentInput = {
  registrationNumber: string;
  registrationDate: IsoDateString;
  title: string;
  about1?: string;
  about2?: string | null;
  kind: DocumentKind;
  description?: string | null;
  incomingNumber?: string | null;
  outgoingNumber?: string | null;
  outgoingDate?: IsoDateString | null;
  employerId?: number | null;
  outSenderEmployerId?: number | null;
  broadcast?: string;
  ownerId: number;
  executorId: number;
  dueDate?: IsoDateString;
  isControl?: boolean;
};
export type UpdateDocumentInput = {
  registrationNumber?: string;
  registrationDate?: IsoDateString;
  title?: string;
  about1?: string;
  about2?: string | null;
  kind?: DocumentKind;
  description?: string | null;
  incomingNumber?: string | null;
  outgoingNumber?: string | null;
  outgoingDate?: IsoDateString | null;
  employerId?: number | null;
  outSenderEmployerId?: number | null;
  broadcast?: string;
  ownerId?: number;
  executorId?: number;
  dueDate?: IsoDateString;
  status?: DocumentStatus;
  isControl?: boolean;
};
